plugins {
	id 'java-library'
	id 'io.spring.dependency-management'
}

group = 'com.mirae'
version = '0.0.1-SNAPSHOT'

java {
	toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

repositories { mavenCentral() }

dependencyManagement {
	imports {
		mavenBom "org.springframework.boot:spring-boot-dependencies:3.3.5" // 루트 Boot 버전과 통일
	}
}

dependencies {
	api 'org.springframework.boot:spring-boot-starter-validation'
	api "org.springframework:spring-web"

	implementation "org.springframework:spring-webmvc"

	// IDE 빨간줄 방지용(런타임은 소비 모듈의 starter-web이 제공)
	compileOnly "jakarta.servlet:jakarta.servlet-api"
	compileOnly "jakarta.validation:jakarta.validation-api"


	compileOnly 'org.projectlombok:lombok:1.18.34'
	annotationProcessor 'org.projectlombok:lombok:1.18.34'
	testCompileOnly 'org.projectlombok:lombok:1.18.34'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

}

tasks.named('test') { useJUnitPlatform() }